# Generated by Django 4.2.7 on 2023-11-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookapp', '0002_remove_book_customer_delete_book_data_delete_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('pieces', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('aadhar', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Shoping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.IntegerField(default=1)),
                ('total', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book_store')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.customer')),
            ],
        ),
    ]
