# Generated by Django 4.2.7 on 2023-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar',
            field=models.IntegerField(),
        ),
    ]
