# Generated by Django 4.2.7 on 2023-11-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_customer_aadhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoping',
            name='total',
        ),
    ]
