# Generated by Django 4.2.7 on 2023-12-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_remove_shoping_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoping',
            name='book',
        ),
        migrations.RemoveField(
            model_name='shoping',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Shoping',
        ),
    ]
